# Generated by Django 3.1.4 on 2022-08-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0002_auto_20220804_0858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shortener',
            new_name='URL',
        ),
    ]
