# Generated by Django 3.1.4 on 2022-08-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0003_auto_20220805_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='ckicks',
            field=models.IntegerField(default=0),
        ),
    ]
