# Generated by Django 3.1.4 on 2022-08-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0004_url_ckicks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='ckicks',
        ),
    ]
